# session + daemons
exec-once = systemctl --user start hyprland-session.target
exec-once = hyprpolkitagent
exec-once = swayosd-libinput-backend
exec-once = playerctld daemon
exec-once = awww-daemon
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# project daemons
exec-once = cp ~/Projects/lyrics/target/release/lyrics ~/.local/bin/lyrics
exec-once = lyrics --json
exec-once = astrium watch --interval 200
exec-once = ~/.config/hypr/scripts/volume_listener.sh

# shells
exec-once = hyprctl dispatch exec "quickshell -p $HOME/.config/hypr/scripts/quickshell/Shell.qml"
exec-once = ~/Projects/zerkal/zerkal.sh start
exec-once = ~/.config/hypr/scripts/applauncher/launcher.sh start
exec-once = python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py
