$mainMod = SUPER
$terminal = kitty
$browser = chromium
$qsm = ~/.config/hypr/scripts/qs_manager.sh

# apps
bind = $mainMod, SPACE, exec, $terminal
bind = $mainMod, E, exec, $browser
bind = $mainMod, R, exec, wofi --show drun

# window control
bind = $mainMod, Q, killactive
bind = $mainMod, F, togglefloating

# workspaces
bind = $mainMod, 1, exec, $qsm 1
bind = $mainMod, 2, exec, $qsm 2
bind = $mainMod, 3, exec, $qsm 3
bind = $mainMod, 4, exec, $qsm 4
bind = $mainMod, 5, exec, $qsm 5
bind = $mainMod, 6, exec, $qsm 6
bind = $mainMod, 7, exec, $qsm 7
bind = $mainMod, 8, exec, $qsm 8
bind = $mainMod, 9, exec, $qsm 9
bind = $mainMod, 0, exec, $qsm 10

# move window to workspace
bind = $mainMod SHIFT, 1, exec, $qsm 1 move
bind = $mainMod SHIFT, 2, exec, $qsm 2 move
bind = $mainMod SHIFT, 3, exec, $qsm 3 move
bind = $mainMod SHIFT, 4, exec, $qsm 4 move
bind = $mainMod SHIFT, 5, exec, $qsm 5 move
bind = $mainMod SHIFT, 6, exec, $qsm 6 move
bind = $mainMod SHIFT, 7, exec, $qsm 7 move
bind = $mainMod SHIFT, 8, exec, $qsm 8 move
bind = $mainMod SHIFT, 9, exec, $qsm 9 move
bind = $mainMod SHIFT, 0, exec, $qsm 10 move

# mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# screenshot
bind = SUPER_SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy

# tile all on active workspace
bind = SUPER, T, exec, ws=$(hyprctl activeworkspace -j | jq -r '.id'); hyprctl clients -j | jq -r --argjson ws "$ws" '.[] | select(.workspace.id == $ws) | .address' | while read addr; do hyprctl dispatch settiled address:$addr; done

# quickshell popups / overlays
bind = SUPER, P, exec, $qsm toggle wallpaper
bind = $mainMod, S, exec, bash $qsm toggle calendar
bind = $mainMod, M, exec, bash $qsm toggle music
bind = $mainMod, N, exec, bash $qsm toggle network
bind = $mainMod, V, exec, bash $qsm toggle volume
bind = SUPER, O, exec, ~/Projects/zerkal/zerkal.sh toggle
