windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = obs-transparent
    match:class = ^(com\.obsproject\.Studio)$
    opacity = 0.75 0.75
}

windowrule {
    name = chrome-transparent
    match:class = ^(chromium|Chromium|google-chrome|Google-chrome)$
    opacity = 0.85 0.75
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
